[skip ci] restrict using git commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,12 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+[ -f '.git/commit-safe' ] || {
+  echo '[ERROR] Please, use the following command for committing:'
+  echo '$ node git-commit <options>'
+  exit 1
+}
+
 npm run build
 npm run test
 prettier --write .
