[skip ci] format pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,9 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 [ -f '.git/commit-pkg' ] || {
-  echo '[ERROR] Please, use the following command for committing:'
-  echo '$ npx git-commit-pkg'
-  exit 1
+	echo '[ERROR] Please, use the following command for committing:'
+	echo '$ npx git-commit-pkg'
+	exit 1
 }
 
 bun run build
